OVER_VOLTAGE_ALARM = 1
UNDER_VOLTAGE_ALARM = 2
OVER_TEMPERATURE_ALARM = 3
UNDER_TEMPERATURE_ALARM = 4
BALANCE_ALARM = 5

OVER_VOLTAGE_WARNING = 6
UNDER_VOLTAGE_WARNING = 7
OVER_TEMPERATURE_WARNING = 8
UNDER_TEMPERATURE_WARNING = 9
BALANCE_WARNING = 10
